# WEB="/home/sxn91401/JAVA/codility/src/main/java"
WEB="/home/sxn91401/gradlePractice/build/reports/tests/test"
RESTART_POLICY="always"
EXPORT_PORT="11147"
CONTAINER_NAME="web"
MOUNT_CONFIG="/home/sxn91401/web/config/default.conf:/etc/nginx/conf.d/default.conf"
MOUNT_DIR="${WEB}:/usr/share/nginx/html:ro"
